# Generated by Django 3.2.5 on 2021-11-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_image_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.CreateModel(
            name='ImageCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=500, null=True)),
                ('fontcolor', models.TextField(max_length=500, null=True)),
                ('position_x', models.IntegerField(null=True)),
                ('position_y', models.IntegerField(null=True)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='gallery.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_caption', to='gallery.imagecaption'),
            preserve_default=False,
        ),
    ]
