# Generated by Django 3.2.5 on 2021-11-21 05:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('gallery', '0005_auto_20211121_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCaption',
            new_name='Caption',
        ),
    ]
