# Generated by Django 3.2.5 on 2021-11-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_caption', to='gallery.caption'),
        ),
    ]
