# Generated by Django 3.2.5 on 2021-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20211121_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
