# Generated by Django 3.2.5 on 2021-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20211121_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='caption',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
