# Generated by Django 3.2.5 on 2021-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_caption_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='caption',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
